name: acma_intl
description: "Application to manage employee wages, clients bills and company stocks."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  firebase_database: ^11.1.0
  firebase_storage: ^12.2.0
  image_picker: ^1.1.2
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  get_storage: ^2.1.1
  cached_network_image: ^3.4.1
  local_auth: ^2.3.0
  http: ^1.2.2
  flutter_advanced_drawer: ^1.3.6
  google_nav_bar: ^5.0.6
  path_provider: ^2.1.4
  font_awesome_flutter: ^10.7.0
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.2
  screenshot: ^3.0.0
  pdf: ^3.11.1
  get: ^4.6.6
  cupertino_icons: ^1.0.8
  package_info_plus: ^8.0.2
  url_launcher: ^6.3.0

  flutter_launcher_icons: "^0.13.1"
flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/appIcon.png"
  min_sdk_android: 21


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
